k8s-onboarding:
  replicaCount: 2
  image:
    tag: master
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: testargo.insee.io
        paths:
          - /
    tls:
      - hosts:
          - testargo.insee.io
